export const SIMULATION_REQUEST_SUCCESS = 'SIMULATION_REQUEST_SUCCESS';
export const SIMULATION_REQUEST_FAIL = 'SIMULATION_REQUEST_FAIL';
export const INIT_EXTEND_DATA_SUCCESS = 'INIT_EXTEND_DATA_SUCCESS';
export const INIT_EXTEND_DATA_FAIL = 'INIT_EXTEND_DATA_FAIL';
export const SAVE_EXTEND_DATA_SUCCESS = 'SAVE_EXTEND_DATA_SUCCESS';